# Generated by Django 5.1.1 on 2024-10-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_alter_servicerequest_quote_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_completed_file',
        ),
    ]
