# Generated by Django 5.1.1 on 2024-11-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0003_remove_document_is_completed_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='quote_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
