# Generated by Django 5.1.1 on 2024-11-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0005_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
